### ISSUE TITLE
undefined method `printful_variant_id' for #<Spree::Variant:0x00007fd972cf0640> Did you mean? printful_printfile

### ISSUE THREAD

**Issue by mcfiredrill** [lemuelbarango/spree_printful#3]
Hi I get this error when trying to create a new product in the admin dashboard.

```
undefined method `printful_variant_id' for #<Spree::Variant:0x00007fd972cf0640> Did you mean? printful_printfile
```

trace
```
activemodel (5.1.6) lib/active_model/attribute_methods.rb:432:in `method_missing'
/Users/tony/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/spree_printful-727e8a9c3f78/app/models/spree/variant_decorator.rb:42:in `printful_has_variant'
activesupport (5.1.6) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.6) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
activesupport (5.1.6) lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
activesupport (5.1.6) lib/active_support/callbacks.rb:600:in `catch'
activesupport (5.1.6) lib/active_support/callbacks.rb:600:in `block in default_terminator'
activesupport (5.1.6) lib/active_support/callbacks.rb:198:in `block in halting'
activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `block in invoke_before'
activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `each'
activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `invoke_before'
activesupport (5.1.6) lib/active_support/callbacks.rb:130:in `run_callbacks'
activesupport (5.1.6) lib/active_support/callbacks.rb:827:in `_run_validate_callbacks'
activemodel (5.1.6) lib/active_model/validations.rb:405:in `run_validations!'
activemodel (5.1.6) lib/active_model/validations/callbacks.rb:114:in `block in run_validations!'
activesupport (5.1.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
activesupport (5.1.6) lib/active_support/callbacks.rb:827:in `_run_validation_callbacks'
activemodel (5.1.6) lib/active_model/validations/callbacks.rb:114:in `run_validations!'
activemodel (5.1.6) lib/active_model/validations.rb:335:in `valid?'
activerecord (5.1.6) lib/active_record/validations.rb:65:in `valid?'
spree_core (3.4.4) app/models/spree/product.rb:350:in `validate_master'
activesupport (5.1.6) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.6) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
activesupport (5.1.6) lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
activesupport (5.1.6) lib/active_support/callbacks.rb:600:in `catch'
activesupport (5.1.6) lib/active_support/callbacks.rb:600:in `block in default_terminator'
activesupport (5.1.6) lib/active_support/callbacks.rb:198:in `block in halting'
activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `block in invoke_before'
activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `each'
activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `invoke_before'
activesupport (5.1.6) lib/active_support/callbacks.rb:130:in `run_callbacks'
activesupport (5.1.6) lib/active_support/callbacks.rb:827:in `_run_validation_callbacks'
activemodel (5.1.6) lib/active_model/validations/callbacks.rb:114:in `run_validations!'
activemodel (5.1.6) lib/active_model/validations.rb:335:in `valid?'
activerecord (5.1.6) lib/active_record/validations.rb:65:in `valid?'
activerecord (5.1.6) lib/active_record/validations.rb:82:in `perform_validations'
activerecord (5.1.6) lib/active_record/validations.rb:44:in `save'
activerecord (5.1.6) lib/active_record/attribute_methods/dirty.rb:35:in `save'
activerecord (5.1.6) lib/active_record/transactions.rb:308:in `block (2 levels) in save'
activerecord (5.1.6) lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/tony/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
activerecord (5.1.6) lib/active_record/transactions.rb:210:in `transaction'
activerecord (5.1.6) lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
activerecord (5.1.6) lib/active_record/transactions.rb:308:in `block in save'
activerecord (5.1.6) lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
activerecord (5.1.6) lib/active_record/transactions.rb:307:in `save'
activerecord (5.1.6) lib/active_record/suppressor.rb:42:in `save'
globalize (5.1.0) lib/globalize/active_record/instance_methods.rb:148:in `block (2 levels) in save'
globalize (5.1.0) lib/globalize/active_record/instance_methods.rb:212:in `without_fallbacks'
globalize (5.1.0) lib/globalize/active_record/instance_methods.rb:147:in `block in save'
globalize (5.1.0) lib/globalize.rb:27:in `with_locale'
globalize (5.1.0) lib/globalize/active_record/instance_methods.rb:146:in `save'
spree_backend (3.4.4) app/controllers/spree/admin/resource_controller.rb:48:in `create'
actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
railties (5.1.6) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.6) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
versioncake (3.3.0) lib/versioncake/rack/middleware.rb:17:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.4) lib/rack/etag.rb:25:in `call'
rack (2.0.4) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.4) lib/rack/head.rb:12:in `call'
rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
puma (3.11.2) lib/puma/configuration.rb:225:in `call'
puma (3.11.2) lib/puma/server.rb:624:in `handle_request'
puma (3.11.2) lib/puma/server.rb:438:in `process_client'
puma (3.11.2) lib/puma/server.rb:302:in `block in run'
puma (3.11.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Request
Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"QIQdWzWo2UpK+0DzXH3TT4zZ2X3D2OeuxGaQU0pXIHv30R0XaIbDU1dI7gvzW0VIMrhCHVIs/JeShL4stAcrcg==",
 "product"=>{"name"=>"melted cheese", "sku"=>"", "prototype_id"=>"", "price"=>"55", "available_on"=>"2018/04/18", "shipping_category_id"=>"1"},
 "button"=>""}

```

**Comment by mcfiredrill** [comment]
Ah sorry, forgot to install the migration!
